on:
  push:
    branches:
      - main
      - master
  schedule:
  - cron: '*/5 * * * *' # Runs every day at midnight  # Runs every day at midnight
  - cron: '0 17 * * 4'  # Thursday at 5 PM UTC
  - cron: '0 21 * * 4'  # Thursday at 9 PM UTC
  - cron: '0 17 * * 5'  # Friday at 5 PM UTC
  - cron: '0 21 * * 5'  # Friday at 9 PM UTC
  - cron: '0 17 * * 0'  # Sunday at 5 PM UTC
  - cron: '0 21 * * 0'  # Sunday at 9 PM UTC
jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run your script
      env:
        URL: ${{ secrets.URL }}
        GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        RECEPIENTS: ${{ secrets.RECEPIENTS }} 
      run: |
        # Add your script commands here
        echo "Running scheduled task..."
        # Example: python your_script.py
        python lambda_function.py
